version: "3.8"
services:
  backend:
    build: ./backend  # Flask backend
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongo  # Ensure MongoDB starts before the backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/  # MongoDB connection string as an environment variable

  frontend:
    build: ./frontend  # Nginx frontend
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - backend  # Make sure the backend is up before starting Nginx
    networks:
      - app_network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db  # Persistent storage for MongoDB
    ports:
      - "27017:27017"
    networks:
      - app_network

volumes:
  mongo-data:

networks:
  app_network:
    driver: bridge
