# Use the official Nginx image
FROM nginx:latest

# Copy the HTML files to the Nginx server's default directory
COPY index.html /usr/share/nginx/html/index.html
#COPY ./styles.css /usr/share/nginx/html/styles.css  # if you have styles
#COPY ./scripts.js /usr/share/nginx/html/scripts.js  # if you have JS

# Copy custom Nginx configuration file
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose the port Nginx is running on
EXPOSE 80
