

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: flask-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "8989:80"
    container_name: nginx-frontend
